Lesson311 modified
Polpetta/Bioinformatic1 pull request #18
Opened 2017-02-07 19:37 UTC by EmanueleC

**Reference to the issue (if any)**: #17 

**Description**

2017-02-08 08:59 UTC, Polpetta requested changes
To finish section "Algorithms to map reads on a reference genome"

2017-02-15 20:35 UTC, Polpetta commented
@EmanueleC appena finita sta sezione avvisami che mergio

2017-02-16 15:52 UTC, EmanueleC commented
Mergia, apriremo una issue separata per l'occasione.

2017-02-16 15:56 UTC, Polpetta approved these changes
Ricordarsi aggiungere sezione mancante

2017-02-16 15:57 UTC, merged