Lesson411 modified
Polpetta/Bioinformatic1 pull request #23
Opened 2017-02-10 11:24 UTC by EmanueleC

**Reference to the issue (if any)**: #22

**Description** It should be checked out the missing word in the slide

2017-02-13 07:41 UTC, Polpetta commented
@EmanueleC in che senso? :blush:

2017-02-14 09:59 UTC, EmanueleC commented
@Polpetta nelle slide c'è scritto "otherwise the [parola mancante] would occur". Io ho scritto "overlap" al posto di [parola mancante]. Secondo te va bene? Guarda [questo](https://github.com/Polpetta/Bioinformatic1/commit/390d1550d94880a940d2b57b3fff5ac45555883b#comments) commit

2017-02-16 15:02 UTC, Polpetta commented
@EmanueleC ho letto la slide. Anche secondo me e' `overlap`. Un'altra possibilita' e' che sia `match`, ma non ci sta benissimo. Che facciamo? 😊 

Carico [qui comunque la slide incriminata](https://github.com/Polpetta/Bioinformatic1/files/780474/NGS_genome_assembly_2016.pdf) (per completezza)

2017-02-16 15:32 UTC, Polpetta requested changes
Appena capiamo che parola ci va nella slide e' da mergiare

2017-02-16 15:45 UTC, Polpetta commented
Come suggerito da @EmanueleC intanto mergio cosi', poi vedremo se la parola `overlap` e' giusta! 😅

2017-02-16 15:45 UTC, EmanueleC commented
Lascia overlap

2017-02-16 15:46 UTC, Polpetta approved these changes
Memo: chiedere al prof se la parola mancante nella slide e' `overlap`

2017-02-16 15:48 UTC, merged