Assembly exercise added
Polpetta/Bioinformatic1 pull request #41
Opened 2017-02-15 11:31 UTC by EmanueleC

**Reference to the issue (if any)**: #40

**Description**

2017-02-15 11:44 UTC, EmanueleC commented
Anche qui ho un dubbio, se considero le due reads TTTT e GGGG, in realtà la sequenza finale non è TTCTACCTGATTTCGGGAACTT ma TTCTACCTGATTTTCGGGGAACTT (una T e una G in più in mezzo).
Inoltre non ho risposto in modo esauriente alle domande :(

2017-02-15 20:51 UTC, Polpetta commented
Allora aspettiamo a mergiarla. Spero di riuscire a fare l'esercizio entro il 17 come ti ho detto su slack! 😞 Cosi' almeno sappiamo se ci viene lo stesso risultato

2017-02-15 20:51 UTC, Polpetta requested changes
Da provare a vedere se viene lo stesso risultato

2017-02-21 17:51 UTC, Polpetta approved these changes

2017-02-21 17:51 UTC, Polpetta commented on res/sections/82-QA.tex
> +Pheraps the reads \texttt{TTTT} and \texttt{GGGG} should be considered as
No `reads` ma `kmers`

2017-02-21 17:51 UTC, Polpetta commented on res/sections/82-QA.tex
> +  \Question \texttt{{\color{red} TTC}TACCTGAT{\color{red} TTC}GGGAACTT}
Qui come suggerito da @EmanueleC dovrebbero esserci una T e una G in piu'

2017-02-21 17:53 UTC, EmanueleC commented on res/sections/82-QA.tex
> +  \Question \texttt{{\color{red} TTC}TACCTGAT{\color{red} TTC}GGGAACTT}
No, no! Va bene così ma bisogna togliere le ultime due T

2017-02-21 17:59 UTC, Polpetta approved these changes

2017-02-21 18:04 UTC, merged